# Generated by Django 5.1.6 on 2025-03-16 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0002_delete_feature_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('President', 'President'), ('VPE', 'VPE'), ('VPM', 'VPM'), ('VPPR', 'VPPR'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('SAA', 'SAA')], max_length=50)),
                ('leader_no', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
