# Generated by Django 5.1.6 on 2025-03-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tmapp", "0002_delete_feature_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "get_latest_by": "created_at",
            },
        ),
    ]
