# Generated by Django 5.1.6 on 2025-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0003_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrole',
            name='evaluated_speech_project',
            field=models.CharField(blank=True, help_text='Specify CC project evaluated (e.g., CC1, CC2, ..., CC10)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meetingrole',
            name='focus_point',
            field=models.CharField(blank=True, help_text='Optional evaluation focus (e.g., timing, filler words)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingrole',
            name='meeting_attire',
            field=models.CharField(blank=True, help_text='e.g., Formal, Casual, Kitenge', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingrole',
            name='speech_project',
            field=models.CharField(blank=True, help_text='Specify CC project (e.g., CC1, CC2, ..., CC10)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meetingrole',
            name='speech_title',
            field=models.CharField(blank=True, help_text='Optional speech title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingrole',
            name='word_of_the_day',
            field=models.CharField(blank=True, help_text='Optional Word of the Day', max_length=50, null=True),
        ),
    ]
