# Generated by Django 5.1.6 on 2025-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0004_meetingrole_evaluated_speech_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrole',
            name='evaluated_speech_project',
            field=models.CharField(blank=True, help_text='Specify CC project evaluated (e.g., CC1 - CC10)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrole',
            name='speech_project',
            field=models.CharField(blank=True, choices=[('CC1', 'CC1'), ('CC2', 'CC2'), ('CC3', 'CC3'), ('CC4', 'CC4'), ('CC5', 'CC5'), ('CC6', 'CC6'), ('CC7', 'CC7'), ('CC8', 'CC8'), ('CC9', 'CC9'), ('CC10', 'CC10')], help_text='Specify CC project (e.g., CC1 - CC10)', max_length=10, null=True),
        ),
    ]
