# Generated by Django 5.1.6 on 2025-03-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0006_alter_meetingrole_evaluated_speech_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrole',
            name='is_absent',
            field=models.BooleanField(default=False, help_text='Mark as absent if not attending'),
        ),
    ]
