# Generated by Django 5.1.6 on 2025-03-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0007_meetingrole_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_plan',
            field=models.CharField(choices=[('Semester', 'Ksh300 per semester'), ('Yearly', 'Ksh550 per academic year'), ('Daily', 'Ksh1 per day')], max_length=10),
        ),
    ]
